### PR TITLE
Fix typo in titanium code. Only try JSONP if not titanium.

### PR DESCRIPTION
**Pull request by cianclarke**

### CODE REVIEW

**Comment by cianclarke** [comment]
@wei-lee Any chance you could review this? 
Also, should I be seeing so much diff after doing a generate run? My only changes are in `src/modules/*`,  and yet huge amounts of diff in dist/* - has the build task just not been run in a while?

**Comment by wei-lee** [comment]
@cianclarke  reviewed. Yeah, don't worry about the generated files, they are changed everytime when the build task runs. 

Apparently Testling is not working anymore, I don't know why. I am planning to move the build to travis at some time this week or next week. I will then merge all the current open PRs and get them released.

**Comment by wei-lee** [comment]
@cianclarke  could you rebase your branch using FHMOBSDK-57-support-mbaas-auth and create the PR against it? That branch will be release soon. I am consolidating all the open PRs together.

**Comment by cianclarke** [comment]
@wei-lee Sure, see https://github.com/feedhenry/fh-js-sdk/pull/118 - maybe close this once happy with it?

**Pull request closed without merging**
