### PR TITLE
Remove titanium option

### PR DESCRIPTION
**Pull request by sedroche**
# Motivation
As per ticket [FH-3250](https://issues.jboss.org/browse/FH-3250) we are no longer supporting Titanium/appcelerator apps.

### CODE REVIEW

**Comment by sedroche** [comment]
Are these docs auto-generated or do i need to remove them manually?
https://github.com/feedhenry/fh-js-sdk/blob/master/doc/index.html#L73

**Comment by sedroche** [comment]
As this is a major version bump this is PR is on hold until releasing 3.0

**Comment by wtrocki** [comment]
Looks like forgoten PR. Changes seems to be ok.

**Comment by jcesarmobile** [comment]
It's not forgotten, it's on hold for the 3.0 release as removing Titanium is a breaking change

**Comment by pb82** [comment]
@camilamacedo86 changes look good, but doesn't this require a major version bump?

**Comment by camilamacedo86** [comment]
HI folks, now that it has the major version bumped, could we merge this one? 
Please, could someone check and approve it?
c/c @jcesarmobile @wtrocki  @pb82

**Comment by wtrocki** [comment]
@camilamacedo86 - Best to get @sedroche approval and merge that. It's really old PR. 
I'm not comfortable to get that merged. Is that PR still needed/required?

**Comment by sedroche** [comment]
@camilamacedo86 @wtrocki @davidffrench 
I am not sure I can give approval to merge this as I would defer to someone with greater knowledge of the sdk but all other related PRs are merged and appcelerator/titanium has been removed

**Comment by davidffrench** [comment]
I am not familiar with what titanium was used for and what it means now that it is still in the sdk but removed from the platform.

Is this still a breaking change if removed from the sdk if it is already removed from the platform?

**Comment by camilamacedo86** [comment]
Hi @flashlee,

Here we have a PR which is updated with the master and all done to be merged. Previously, it got a-ok in the changes performed from @witmicko, @pb82 @jcesarmobile. However, it was missing bump the version and add the changelog, which all is done now. 

@sedroche cannot approve since he is the owner of the PR and @davidffrench was not too familiar with it. In this way, since you @flashlee is the reporter of this JIRA could you verify the PR for we are able to move forward and merge it? 

@davidffrench I think it should be merged a while when it was removed from the platform and we forgot it :-(. IHMO we could move forward safely here since it was removed from RHMAP a while (Apr/17).

**Comment by davidffrench** [comment]
I can't see any reason to not merge this in with the major version bump. I would be curious why it wasn't released before and was waiting on the 3.0.0 release. Were there other changes @jcesarmobile that were meant to be included in a 3.0.0 release?

**Comment by jcesarmobile** [comment]
The initial idea of 3.0.0 was to remove the automatic init and make users call init themselves to align with the native SDKs (see https://github.com/feedhenry/fh-js-sdk/pull/176) 
But that was always postponed for the next release, and again, and again, at first because studio had a button to update the SDK and we didn't want users to update to a major version by clicking that button as that will break the app, and when the button was removed because we didn't want to introduce this kind of breaking changes on the RHMAP release (as it also meant to update all the templates) and was always postponed for the next one.

That PR is closed now. 

Not sure if people is still interested in removing the auto init at some point in the future or if that idea has been discarded.
In case the idea has been discarded, there is a bunch of issues about the SKD update on the templates that can be closed. 
In case it's just postponed once again, the epic and issues should be renamed to refer to the next version 4.0 instead of the 3.0.

I sent a mail about the 3.0 release to a few mail lists (don't remember which ones and I can no longer check it, but @wtrocki probably knows as I think he answered)

**Comment by camilamacedo86** [comment]
@davidffrench any objection for we move forward here?
* PR approved by the reporter of the  FH-3250 we are no longer supporting Titanium/Appcelerator apps.
* Updated with master, has changelog and bumped version
* OK in the code review made for 3 people. 

Let's do the merge?

**Comment by davidffrench** [comment]
@camilamacedo86 based on the feedback from individuals more knowledgeable than myself on this PR, i can't see any reason not to merge it.

**Comment by camilamacedo86** [comment]
@davidffrench cool :-) tks

**Pull request merged**
