### PR TITLE
add browserify-shim as a dependency

### PR DESCRIPTION
**Pull request by evanshortiss**
Referenced in #210 -  We need this to be able to bundle `fh-js-sdk` in other projects using browserify.

### CODE REVIEW

**Comment by evanshortiss** [comment]
I noticed out templates work around this by adding `browserify-shim` as a dependency[1], but I'm not sure folks should need to figure this out via an error. I think either we need to set it as a `peerDependency` or a `dependency` as this PR does.

[1] - https://github.com/feedhenry-templates/helloworld-app/blob/master/package.json#L8

**Comment by wtrocki** [comment]
@evanshortiss - I checked this change and I do not see any problems with merge, but I will want to see @jcesarmobile opinion here before we merge.

**Comment by jcesarmobile** [comment]
I agree, `browserify -o www/dist/vendor.js -r fh-js-sdk` should work without needing to add any dependency or devDependency on the project trying to run it (other than fh-js-sdk itself).
So I'm +1 with this change.

But probably some people with more experience than I on the fh-js-sdk should also comment

@nialldonnellyfh @wei-lee, what do you think about this?

**Comment by wei-lee** [comment]
I am ok with this change too

**Comment by evanshortiss** [comment]
Thanks folks!

**Pull request merged**
