### PR TITLE
Update LICENSE to Apache License

### PR DESCRIPTION
**Pull request by johnfriz**

### CODE REVIEW

**Comment by matzew** [comment]
ZOMG! :tada: 

:+1:

**Comment by jasonmadigan** [comment]
@johnfriz was this tested in a cluster? Where is the fhcap PR?

**Comment by jasonmadigan** [comment]
:trollface:

**Comment by johnfriz** [comment]
:smile:

**Comment by grdryn** [comment]
@johnfriz Just to confirm, should this have the boilerplate file header that's mentioned in the appendix of the LICENSE file, in each of the files that the license covers? Otherwise (alluding to the opening sentence of the appendix) is the license properly applied to our work?

**Comment by johnfriz** [comment]
Hi @grdryn - ultimately, yes. However, main focus for now is to get us over to an open source license. We will need to schedule the adding of the headers - PRs welcome :smile:

**Comment by grdryn** [comment]
@johnfriz cool, thanks.

cc @nialldonnellyfh (relating to a comment I left in your PR earlier)

**Pull request merged**
