### PR TITLE
added wrapper around AeroGear-Push-Titanium module

### PR DESCRIPTION
**Pull request by edewit**
@wei-lee added this for push

### CODE REVIEW

**Comment by edewit** [comment]
@wei-lee can you have a look?

**Comment by jcesarmobile** [comment]
It only adds a wrapper for `registerDevice`, there are other 4 functions provided by Titanium (`getToken`, `unregisterDevice`, `subscribeDevice` and `trackPushOpenEvent`). Is that ok?

fail is never used. Looking into AeroGear-Push-Titanium it has a `deviceTokenError` function, but it won't execute any callback, just logs the error.

**Comment by edewit** [comment]
@jcesarmobile unregisterDevice only works on android, so didn't include it. I didn't include the other functions as the idea of UPS is to make push as simple as possible without the need to know about tokens.

**Comment by jcesarmobile** [comment]
Then LGTM

**Pull request merged**
