### PR TITLE
bower support

### PR DESCRIPTION
**Pull request by shannonmpoole**
So this is just an update for bower support. I did notice that there is a seemingly random release tagged 3.25.0+155. This is really messing with bower semver check so it's thinking that's the newest release and throws mismatch warnings at the user. I'm not sure if there's anything we can/want to do about that.

I didn't bother bumping to 2.7.5 as this can be sort of parallel to any npm release but let me know if you'd like me to bump package.json and bower.json to 2.7.5.

### CODE REVIEW

**Comment by mmurphy** [comment]
This update looks minor, any thoughts from @nialldonnellyfh and @wei-lee, especially about the 3.x tags mentioned in the description?

**Comment by elebetsamer** [comment]
This is a big blocker for using the feed henry js sdk effectively. Right now I have to check in the bower_components folder in to my repo in order to avoid my other developers having to do an npm install and grunt build in the bower_components/fh-js-sdk.

This is a pretty simple PR, so please merge it as soon as possible.

Thanks.

**Comment by wei-lee** [comment]
merged in 75fd4546988b0b1e24a439f48708458d05bdbf4a

**Comment by wei-lee** [comment]
@nialldonnellyfh  any idea about the 3.x tags? If it's not used anymore, can we remove them?

**Comment by nialldonnellyfh** [comment]
@wei-lee Yes, I will remove them. No idea where they came from.

**Pull request closed without merging**
