### PR TITLE
FH-3063 Apply fix from amoran

### PR DESCRIPTION
**Pull request by david-martin**

### CODE REVIEW

**Comment by david-martin** [comment]
@alanmoran I've applied a change that Joe Kenny referred from you.
Can you help with some context on the change?

If an update fails (as dictated by the sync server), is marking the record as crashed so it will try again later the desired default behaviour?

Should the developer instead listen to the `REMOTE_UPDATE_FAILED` notification so they can apply the appropriate behaviour in that scenario?

(cc @wei-lee for thoughts on this too)

Also related, I'm not sure if just marking as crashed is enough for the client to retry later, due to the 'processUpdates' call a little further down which will remove all pending records that were previously inflight (i.e. remove the records that were just marked as crashed)

**Comment by david-martin** [comment]
@alanmoran I'm not sure if this change should make it into master.
I think failed updates should be handled by way of the failed updates event.
If failed updates automatically get rescheduled (by way of marking them crashed), it could overload the Dataset Backend. For example, if the Dataset Backend was down for some time, and clients kept trying to send updates (including any updates that were failed and marked as crashed), it could overload the Dataset Backend when it eventually comes back online.

What are your thoughts on this?

**Comment by alanmoran** [comment]
@david-martin Apologies for the delay. I was meant to come back to this. To be honest I can't remember a huge amount of this issue. 

If I remember correctly the problem here is if the backend is down or returns and error for whatever reason the sync framework was basically dumping the update. 

I don't think I was aware of the ` failed updates` event when I was originally looking at this issue.

I'm not sure if developers should be handling failed events like this. I would expect the sync framework to handle failed updates for me and not just assuming that the developer is handling the failed update via the event handler. (Maybe we need to update the docs here)

Very good point on the overloading though. This is not something I really thought about when looking at this.

**Comment by david-martin** [comment]
@alanmoran How about this:
- If a config value, e.g `mark_failed_as_crashed` is true, mark any failed updates as crashed (so they can be retried later). This would be the default behaviour.
- If the value is false, don't mark them as crashed (the current behaviour), leaving it to the developer to handle the failed updates as they see fit.

cc @wei-lee

**Comment by alanmoran** [comment]
@david-martin That makes sense to me and I would be really happy with that behaviour as a developer. 👍

**Comment by david-martin** [comment]
@alanmoran After proposing this solution to @johnfriz (in the context of other ongoing sync changes), he was against it.
I believe his thinking is its a bad idea to have default behaviour of retrying crashed updates. @johnfriz  any more you can add to this line of thinking?

If we're not going with the proposed change, should anything be changed (leave it up to the developer to listen to failed events).
Should we still add the flag, but switch the default behaviour so you need to 'opt in' to retrying crashed records?

**Comment by johnfriz** [comment]
My view here is that we should not be automatically retrying crashed updates. The sync framework will not be able to determine the reason for the failure or what the business use cases should be in terms of retrying or not. This is something that the developer of the app would need to decide based on the specific use case, so having automagic logic that retries crashed records would not be a suitable approach for all use cases.

In a scenario where the back end data store was unavailable, the proposed logic would case all crashed updates to re-queue,  =which could quite easily result in us DDOSing ourselves.

**Comment by david-martin** [comment]
Closing this PR based on comment from @johnfriz above.

**Pull request closed without merging**
