### PR TITLE
Rhmap 5208 section break description not rendered

### PR DESCRIPTION
**Pull request by lholmquist**
Adds the missing description in the Section Break Header

### CODE REVIEW

**Comment by wei-lee** [comment]
The change looks fine. Please make sure fh-js-sdk version is bumped in the fh-mobile-sdks as well.

**Comment by lholmquist** [comment]
@wei-lee do i need to merge this(and the ngui one) first before i update the fh-mobile-sdks? looking at that readme,  https://github.com/fheng/fh-mobile-sdks, seems like i need a release before running the make

**Comment by wei-lee** [comment]
@lholmquist yes. You can update the mobile sdk as the last step.

**Comment by lholmquist** [comment]
@wei-lee ok, thanks,  i'll start merging all the things

**Comment by lholmquist** [comment]
@wei-lee is there a script or anything that creates the release of GH or is it just a manual process

**Comment by wei-lee** [comment]
@lholmquist you just need to create a git tag using the version number and push it to the remote. Travis will take care of the rest.

**Pull request merged**
