### PR TITLE
Fh 2763.doc.generation

### PR DESCRIPTION
**Pull request by corinnekrych**

### CODE REVIEW

**Comment by corinnekrych** [comment]
To test the PR run:
```
npm i
npm run doc
```
it should create a doc folder and publish it to gh-pages

**Comment by trepel** [comment]
@corinnekrych I am not able to run npm install (or npm i). Keep getting error:
```
$ npm install
npm WARN package.json fh-js-sdk@2.18.4 license should be a valid SPDX license expression
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/home/trepel/.nvm/versions/node/v4.5.0/bin/node" "/home/trepel/.nvm/versions/node/v4.5.0/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /@types/fs-extra was not found on this server.</p>
npm ERR! <hr>
npm ERR! <address>Apache/2.2.31 (Amazon) Server at npm.skunkhenry.com Port 80</address>
npm ERR! </body></html>

```
Any idea what might have gone wrong ?

**Comment by trepel** [comment]
@corinnekrych Thanks Corinne for helping me, the problem was I using npm.skunkhenry as my default registry. When I switched back to default it worked as expected.

I can see my commit in gh-pages branch. Not sure if this is enough for the review, but it looks good to me.

**Comment by corinnekrych** [comment]
thanks @trepel merging it. Better have sth to generate JS doc than nothing. The process can be improved incrementally.

**Pull request merged**
