### PR TITLE
removed call that removes images

### PR DESCRIPTION
**Pull request by edewit**
fixing issue [RHMAP-6428](https://issues.jboss.org/browse/RHMAP-6428)

@nialldonnellyfh don't know if this solution is sound, but it works ;)

### CODE REVIEW

**Comment by nialldonnellyfh** [comment]
Yes, that makes sense to me.

Can you bump the version of the js-sdk for the PR

**Comment by nialldonnellyfh** [comment]
Sorry, forgot to mention the changelog.

**Comment by edewit** [comment]
@nialldonnellyfh updated the change log, but wouldn't it be better to have this info in jira?

**Comment by nialldonnellyfh** [comment]
@edewit Looks good. 

This is a public repo so it makes sense to keep a change log.

**Comment by nialldonnellyfh** [comment]
@edewit Can you rebase and merge to master when you get a chance.

**Comment by edewit** [comment]
@nialldonnellyfh rebased

**Comment by nialldonnellyfh** [comment]
@edewit Looks good.

**Pull request merged**
