### PR TITLE
remove __fh from body/query (issue #149)

### LINKED ISSUE #149: Remove FeedHenry Params in Query/Body
Hey, 

Currently when making a FH.Cloud call the result of FH.getCloudParams is injected to the body/query. This is a highly intrusive behaviour that would be unwanted by people building an API in express since they have to deal with removing these from a query/body.

Placing these in the headers would be much cleaner and it appears we [do that](https://github.com/evanshortiss/fh-js-sdk/blob/master/src/modules/api_cloud.js#L22). I'll take a look to see why this is not being added to my FH.Cloud call headers, but would we be open to removing or adding a config option to prevent the FH.getCloudParams from being injected into user queries/bodies?

@wei-lee

### PR DESCRIPTION
**Pull request by evanshortiss**
This fixes #149 by removing the `__fh` property from req.query and req.body. These values are already in headers so this should be fine 👍

### CODE REVIEW

**Comment by evanshortiss** [comment]
@johnfriz @wei-lee thoughts?

**Comment by wei-lee** [comment]
I would love to remove it. I believe the reasons we have it in the request body are:

1. to work with jsonp. You can set headers for jsonp.
2. to work with IE8. I believe the Cross Domain Request in IE8 doesn't allow setting headers either.

Basicly it is a hack to work with different XHR in different browsers 3-4 years ago. Today I believe most of the modern browsers don't have those problem anymore, and I would love to remove this code.

If it is still a requirement to support jsonp and IE8, perhaps we can at least only add `__fh` part for those 2 scenarios?

@johnfriz @conoro WDYT?

**Comment by conoro** [comment]
@wei-lee  I don't know about jsonp but we definitely have dropped support for IE8.

**Comment by evanshortiss** [comment]
@conoro @wei-lee so perhaps there should be an option to enable/disable this as a "just in case" scenario?

**Comment by wei-lee** [comment]
@evanshortiss that sounds good. We will only add `__fh` if the request is for jsonp.

**Comment by wei-lee** [comment]
LGTM

**Pull request merged**
