### PR TITLE
Updating .travis.yml to use npm@2.13.5, updating Browserify to remove 404'ing sub-dependency

### PR DESCRIPTION
**Pull request by jasonmadigan**

### CODE REVIEW

**Comment by edewit** [comment]
phantomjs is still not happy

**Comment by jasonmadigan** [comment]
@edewit yeah, have a feeling a dev-dep changed, will keep digging

**Comment by jasonmadigan** [comment]
@wei-lee

**Comment by wei-lee** [comment]
:+1:

**Comment by jasonmadigan** [comment]
There was a devDependency sub-dep that had been unpublished in the `browserify` module. Bumping it fixed things - have also made a few small changes to the `.travis.yml` config

**Pull request merged**
